include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Strict rules
    always_declare_return_types: true
    always_specify_types: false # Flutter style usually prefers type inference for local vars, but specify for APIs.
    unawaited_futures: true
    avoid_void_async: true
    library_private_types_in_public_api: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    directives_ordering: true
    lines_longer_than_80_chars: false # Flexible
